version: '2.1'

services:
  db:
    image: mariadb:10.1.21
    environment:
      MYSQL_ROOT_PASSWORD: ABC123XYZ@
      MYSQL_DATABASE: sample_app
      MYSQL_USER: web_user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mariadb/general.cnf:/etc/mysql/conf.d/general.cnf:ro
      - ./sample/schema.sql:/docker-entrypoint-initdb.d/1.sql

  web:
    image: "sample/sample:latest"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      FLASK_APP: app/main.py
      FLASK_DEBUG: 1
      MYSQL_DATABASE: sample_app
      MYSQL_HOST: db
      MYSQL_PASSWORD: password
      MYSQL_USER: web_user
      PYTHONDONTWRITEBYTECODE: 1
      SESSION_MAX_AGE: 259200
      TEMPLATES_AUTO_RELOAD: 1
      UWSGI_HTTP_PORT: 8080
      UWSGI_PROCESSES: 1
      UWSGI_PY_AUTO_RELOAD: 1
      UWSGI_LOGTO: stdout
    ports:
      - "127.0.0.1:80:8080"
    restart: unless-stopped
    volumes:
      - ./sample:/var/code
